services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: telegramcurrency
      MYSQL_USER: telegram
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: telegram
    ports:
      - "33061:3306"
    networks:
      - spring-app-network
    volumes:
      - mysql-data:/var/lib/mysql
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/telegramcurrency
      SPRING_DATASOURCE_USERNAME: telegram
      SPRING_DATASOURCE_PASSWORD: telegram
    ports:
      - "8080:8080"
    networks:
      - spring-app-network
networks:
  spring-app-network:
    driver: bridge

volumes:
  mysql-data:
